version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable
    container_name: recipy_api
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - laravel

  mariadb:
    image: mariadb:10.5.1
    container_name: recipy_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recipy
      MYSQL_USER: recipy
      MYSQL_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: recipy_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: recipy_phpmyadmin
    ports:
      - "8001:80"
    depends_on:
      - mariadb
    environment:
      PMA_HOSTS: mariadb
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: recipy_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:13.10
    container_name: recipy_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: recipy_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
